### ISSUE TITLE
test error 

### ISSUE THREAD

**Issue by c1a1o1** [linjx-ustc1106/DosGAN-PyTorch#1]
1   main_dosgan.py --mode cls  --model_dir dosgan_season_cls --ft_num 64 --c_dim 4 --image_size 256 --train_data_path data/season_train_dir --test_data_path data/season_val_dir`

2 main_dosgan.py --mode train  --model_dir dosgan_season --cls_save_dir dosgan_season_cls/models --ft_num 64 --c_dim 4 --image_size 256 --lambda_fs 0.15 --num_iters 300000 --train_data_path season_train_dir --test_data_path season_val_dir`
   
3E:\Users\Raytine\Anaconda3\python.exe F:/imageedit/DosGAN-PyTorch-master/main_dosgan.py --mode test --model_dir dosgan_season --cls_save_dir dosgan_season_cls/models --train_data_path data/season_train_dir --test_data_path data/season_val_dir
Namespace(batch_size=6, beta1=0.5, beta2=0.999, c_dim=531, cls_save_dir='dosgan_season_cls/models', d_conv_dim=64, d_lr=0.0001, d_repeat_num=6, ft_num=1024, g_lr=0.0001, image_size=128, lambda_fs=5, lambda_gp=10, lambda_rec=10, lambda_rec2=10, log_step=1000, lr_update_step=1000, mode='test', model_dir='dosgan_season', model_save_step=20000, n_blocks=0, n_critic=5, non_conditional=True, num_iters=200000, num_iters_decay=100000, num_workers=1, resume_iters=None, sample_step=2000, test_data_path='data/season_val_dir', test_iters=200000, train_data_path='data/season_train_dir')
train dataset loaded
test dataset loaded
Traceback (most recent call last):
  File "F:/imageedit/DosGAN-PyTorch-master/main_dosgan.py", line 118, in <module>
    main(config)
  File "F:/imageedit/DosGAN-PyTorch-master/main_dosgan.py", line 64, in main
    solver.test1()
  File "F:\imageedit\DosGAN-PyTorch-master\solver_dosgan.py", line 611, in test1
    self.C.load_state_dict(torch.load(C_path, map_location=lambda storage, loc: storage))
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Classifier:
	size mismatch for conv1.0.bias: copying a param of torch.Size([1024]) from checkpoint, where the shape is torch.Size([64]) in current model.
	size mismatch for conv1.0.weight: copying a param of torch.Size([1024, 2048, 2, 2]) from checkpoint, where the shape is torch.Size([64, 2048, 4, 4]) in current model.
	size mismatch for conv2.weight: copying a param of torch.Size([531, 1024, 1, 1]) from checkpoint, where the shape is torch.Size([4, 64, 1, 1]) in current model.

**Comment by zhangqian001** [comment]
> 1 main_dosgan.py --mode cls --model_dir dosgan_season_cls --ft_num 64 --c_dim 4 --image_size 256 --train_data_path data/season_train_dir --test_data_path data/season_val_dir`
> 
> 2 main_dosgan.py --mode train --model_dir dosgan_season --cls_save_dir dosgan_season_cls/models --ft_num 64 --c_dim 4 --image_size 256 --lambda_fs 0.15 --num_iters 300000 --train_data_path season_train_dir --test_data_path season_val_dir`
> 
> 3E:\Users\Raytine\Anaconda3\python.exe F:/imageedit/DosGAN-PyTorch-master/main_dosgan.py --mode test --model_dir dosgan_season --cls_save_dir dosgan_season_cls/models --train_data_path data/season_train_dir --test_data_path data/season_val_dir Namespace(batch_size=6, beta1=0.5, beta2=0.999, c_dim=531, cls_save_dir='dosgan_season_cls/models', d_conv_dim=64, d_lr=0.0001, d_repeat_num=6, ft_num=1024, g_lr=0.0001, image_size=128, lambda_fs=5, lambda_gp=10, lambda_rec=10, lambda_rec2=10, log_step=1000, lr_update_step=1000, mode='test', model_dir='dosgan_season', model_save_step=20000, n_blocks=0, n_critic=5, non_conditional=True, num_iters=200000, num_iters_decay=100000, num_workers=1, resume_iters=None, sample_step=2000, test_data_path='data/season_val_dir', test_iters=200000, train_data_path='data/season_train_dir') train dataset loaded test dataset loaded Traceback (most recent call last): File "F:/imageedit/DosGAN-PyTorch-master/main_dosgan.py", line 118, in main(config) File "F:/imageedit/DosGAN-PyTorch-master/main_dosgan.py", line 64, in main solver.test1() File "F:\imageedit\DosGAN-PyTorch-master\solver_dosgan.py", line 611, in test1 self.C.load_state_dict(torch.load(C_path, map_location=lambda storage, loc: storage)) File "E:\Users\Raytine\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 719, in load_state_dict self.**class**.**name**, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for Classifier: size mismatch for conv1.0.bias: copying a param of torch.Size([1024]) from checkpoint, where the shape is torch.Size([64]) in current model. size mismatch for conv1.0.weight: copying a param of torch.Size([1024, 2048, 2, 2]) from checkpoint, where the shape is torch.Size([64, 2048, 4, 4]) in current model. size mismatch for conv2.weight: copying a param of torch.Size([531, 1024, 1, 1]) from checkpoint, where the shape is torch.Size([4, 64, 1, 1]) in current model.

Are you solve this problem?
